version: '3'
services:
  app:
    image: install-python-fastapi-in-docker
    container_name: install-python-fastapi-in-docker
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - ./src:/src
    command:
      sh -c "python /src/main.py"
