version: '3'
services:
  app:
    image: crud-with-python-fastapi
    container_name: crud-with-python-fastapi
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - ./src:/src
    command:
      sh -c "python /src/main.py"
